//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikCV_ASP.Net_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdres
    {
        public byte ID { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public byte[] adres { get; set; }
        public string konum { get; set; }
    }
}
