//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikCV_ASP.Net_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHakkimda
    {
        public int ID { get; set; }
        public string bilgiler { get; set; }
        public string egitim { get; set; }
        public string deneyimler { get; set; }
    }
}
